name: CI

on:
  push:
    branches:
      - main
      - develop
      - "feature/**"
      - "hotfix/**"
  pull_request:
    branches:
      - main
      - develop

jobs:
  python-ci:
    uses: trivox-io/mini-arcade/.github/workflows/reusable-python-ci.yml@main
    with:
      project_name: deja-bounce
      lint_path: src/deja_bounce
      working_directory: .
      apt_deps: "libsdl2-dev libsdl2-ttf-dev libsdl2-mixer-dev"
